# Generated by Django 4.2.5 on 2023-09-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, default='photos/default_img.png', null=True, upload_to='photos/company_logos/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_image',
            field=models.ImageField(default='photos/default_img.png', upload_to='photos/countries/'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='job_image',
            field=models.ImageField(blank=True, default='photos/default_img.png', null=True, upload_to='photos/job_images/%Y/%m/%d/'),
        ),
    ]
