# Generated by Django 4.2.5 on 2023-09-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_company_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='job_type',
            field=models.CharField(choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='Onsite', max_length=10),
        ),
    ]
