# Generated by Django 4.2.5 on 2023-09-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobprofiles', '0002_companyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='founded_date',
        ),
    ]
